### ISSUE TITLE
suggestion to add a subobject promap helper

### ISSUE THREAD

**Issue by sbergot** [staltz/use-profunctor-state#11]
Hello and thanks for this neat library!

Have you considered adding this little helper?

```
type Promap<T, S> = (get: Getter<T, S>, set: Setter<T, S>, args?: any[]) => ProfunctorState<S>;

function drill<T, K extends keyof T>(promap: Promap<T, T[K]>, key: K) {
    return promap(
        (parent) => parent[key],
        (child, parent) => ({...parent, key: child}));
}
```
I am not sure about the name but I use it a lot.

**Comment by staltz** [comment]
Hi. Thanks for submitting the issue, I appreciate suggestions for improvements! I think this functionality can be provided easily with Ramda's prop/assoc, or your helper function can be published separately. This use-profunctor-state library should only have the core functionality, because as soon as you start adding helpers, then it becomes debatable whether we should add all the other possible helpers you can imagine, and that's out of scope. Hope you understand. :)

**Comment by sbergot** [comment]
@staltz no problem. Just for documentation in case someone else looks into this issue: in the end I created a wrapper funtion like this one:

```
export function wrapFunctor<T>(functor: ProfunctorState<T>): Lens<T> {
    const { state, setState, promap } = functor;
    return {
        state,
        setState,
        promap,
        zoom: (key) => {
            const subFunctor = zoom(functor, key);
            return wrapFunctor(subFunctor);
        }
    }
}

```
